SELECT A.TABLESPACE_NAME "表空间名",
       A.FILE_NAME,
       A.BYTES / 1024 / 1024 "表空间大小(M)",
       (A.BYTES - B.BYTES) / 1024 / 1024 "已使用空间(M)",
       B.BYTES / 1024 / 1024 "空闲空间(M)",
       ROUND(((A.BYTES - B.BYTES) / A.BYTES) * 100, 2) "使用比"
  FROM (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES, FILE_NAME FROM DBA_DATA_FILES GROUP BY TABLESPACE_NAME, FILE_NAME) A,
       (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES, MAX(BYTES) LARGEST FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME) B
 WHERE A.TABLESPACE_NAME = B.TABLESPACE_NAME
 ORDER by A.TABLESPACE_NAME--BY ((A.BYTES - B.BYTES) / A.BYTES) DESC;
