
Create user DATALOAD identified by DATALOAD default tablespace DATALOAD_DAT_LARGE;

GRANT "CONNECT" TO "DATALOAD";
ALTER USER "DATALOAD" DEFAULT ROLE  ALL;

GRANT ALTER ANY INDEX TO "DATALOAD";
GRANT ALTER ANY INDEXTYPE TO "DATALOAD";
GRANT ALTER ANY SEQUENCE TO "DATALOAD";
GRANT CREATE ANY INDEX TO "DATALOAD";
GRANT CREATE ANY INDEXTYPE TO "DATALOAD";
GRANT CREATE ANY PROCEDURE TO "DATALOAD";
GRANT CREATE ANY SEQUENCE TO "DATALOAD";
GRANT CREATE ANY TABLE TO "DATALOAD";
GRANT CREATE ANY TRIGGER TO "DATALOAD";
GRANT CREATE ANY VIEW TO "DATALOAD";
GRANT CREATE PROCEDURE TO "DATALOAD";
GRANT CREATE ROLLBACK SEGMENT TO "DATALOAD";
GRANT CREATE TRIGGER TO "DATALOAD";
GRANT CREATE VIEW TO "DATALOAD";
GRANT DEBUG ANY PROCEDURE TO "DATALOAD";
GRANT DELETE ANY TABLE TO "DATALOAD";
GRANT DROP ANY INDEX TO "DATALOAD";
GRANT DROP ANY INDEXTYPE TO "DATALOAD";
GRANT DROP ANY LIBRARY TO "DATALOAD";
GRANT DROP ANY PROCEDURE TO "DATALOAD";
GRANT DROP ANY SEQUENCE TO "DATALOAD";
GRANT DROP ANY TABLE TO "DATALOAD";
GRANT EXECUTE ANY INDEXTYPE TO "DATALOAD";
GRANT EXECUTE ANY LIBRARY TO "DATALOAD";
GRANT EXECUTE ANY PROCEDURE TO "DATALOAD";
GRANT INSERT ANY TABLE TO "DATALOAD";
GRANT SELECT ANY DICTIONARY TO "DATALOAD";
GRANT SELECT ANY SEQUENCE TO "DATALOAD";
GRANT SELECT ANY TABLE TO "DATALOAD";
GRANT UNDER ANY TABLE TO "DATALOAD";
GRANT UNDER ANY VIEW TO "DATALOAD";
GRANT UPDATE ANY TABLE TO "DATALOAD";
GRANT UNLIMITED TABLESPACE TO "DATALOAD";

GRANT RESOURCE TO "DATALOAD";



GRANT DEBUG ANY PROCEDURE, DEBUG CONNECT SESSION TO DATALOAD;

GRANT IMP_FULL_DATABASE TO DATALOAD;

GRANT DBA TO DATALOAD;


