


Create user GRPT identified by GRPT default tablespace GRPT_DAT;

GRANT "CONNECT" TO "GRPT";
ALTER USER "GRPT" DEFAULT ROLE  ALL;

GRANT ALTER ANY INDEX TO "GRPT";
GRANT ALTER ANY INDEXTYPE TO "GRPT";
GRANT ALTER ANY SEQUENCE TO "GRPT";
GRANT CREATE ANY INDEX TO "GRPT";
GRANT CREATE ANY INDEXTYPE TO "GRPT";
GRANT CREATE ANY PROCEDURE TO "GRPT";
GRANT CREATE ANY SEQUENCE TO "GRPT";
GRANT CREATE ANY TABLE TO "GRPT";
GRANT CREATE ANY TRIGGER TO "GRPT";
GRANT CREATE ANY VIEW TO "GRPT";
GRANT CREATE PROCEDURE TO "GRPT";
GRANT CREATE ROLLBACK SEGMENT TO "GRPT";
GRANT CREATE TRIGGER TO "GRPT";
GRANT CREATE VIEW TO "GRPT";
GRANT DEBUG ANY PROCEDURE TO "GRPT";
GRANT DELETE ANY TABLE TO "GRPT";
GRANT DROP ANY INDEX TO "GRPT";
GRANT DROP ANY INDEXTYPE TO "GRPT";
GRANT DROP ANY LIBRARY TO "GRPT";
GRANT DROP ANY PROCEDURE TO "GRPT";
GRANT DROP ANY SEQUENCE TO "GRPT";
GRANT DROP ANY TABLE TO "GRPT";
GRANT EXECUTE ANY INDEXTYPE TO "GRPT";
GRANT EXECUTE ANY LIBRARY TO "GRPT";
GRANT EXECUTE ANY PROCEDURE TO "GRPT";
GRANT INSERT ANY TABLE TO "GRPT";
GRANT SELECT ANY DICTIONARY TO "GRPT";
GRANT SELECT ANY SEQUENCE TO "GRPT";
GRANT SELECT ANY TABLE TO "GRPT";
GRANT UNDER ANY TABLE TO "GRPT";
GRANT UNDER ANY VIEW TO "GRPT";
GRANT UPDATE ANY TABLE TO "GRPT";
GRANT UNLIMITED TABLESPACE TO "GRPT";

GRANT RESOURCE TO "GRPT";



GRANT DEBUG ANY PROCEDURE, DEBUG CONNECT SESSION TO GRPT;

GRANT IMP_FULL_DATABASE TO GRPT;

GRANT DBA TO GRPT;


