 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT2013.dbf'  offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201301.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201302.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201303.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201304.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201305.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201306.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201307.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201308.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201309.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201310.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201311.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201312.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT2014.dbf'  offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201401.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201402.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201403.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201404.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201405.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201406.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201407.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201408.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201409.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201410.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201411.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201412.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT2015.dbf'  offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201501.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201502.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201503.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201504.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201505.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201506.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201507.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201508.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201509.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201510.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201511.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT201512.dbf'offline drop;

 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT_AUTO.dbf' offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT_LARGE.dbf' offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_DAT_UNIF.dbf' offline drop;

 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND2013.dbf'  offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201301.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201302.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201303.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201304.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201305.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201306.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201307.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201308.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201309.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201310.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201311.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201312.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND2014.dbf'  offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201401.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201402.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201403.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201404.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201405.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201406.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201407.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201408.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201409.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201410.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201411.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201412.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND2015.dbf'  offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201501.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201502.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201503.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201504.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201505.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201506.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201507.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201508.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201509.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201510.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201511.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND201512.dbf'offline drop;

 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND_AUTO.dbf' offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND_LARGE.dbf'offline drop;
 alter database DATAFILE  'D:\iMac\oradata\dataload\DATALOAD_IND_UNIF.dbf' offline drop;
                                                               
