
CREATE  TABLESPACE ORSUSER_IND_TSPACE      DATAFILE  'ORSUSER_IND_TSPACE.dbf'     size 50M Autoextend on next 1024K maxsize unlimited logging Extent management local autoallocate Segment space management auto;
   

Create user ORSUSER_IND identified by ORSUSER_IND default tablespace ORSUSER_IND_TSPACE;

GRANT "CONNECT" TO "ORSUSER_IND";
ALTER USER "ORSUSER_IND" DEFAULT ROLE  ALL;

GRANT ALTER ANY INDEX TO "ORSUSER_IND";
GRANT ALTER ANY INDEXTYPE TO "ORSUSER_IND";
GRANT ALTER ANY SEQUENCE TO "ORSUSER_IND";
GRANT CREATE ANY INDEX TO "ORSUSER_IND";
GRANT CREATE ANY INDEXTYPE TO "ORSUSER_IND";
GRANT CREATE ANY PROCEDURE TO "ORSUSER_IND";
GRANT CREATE ANY SEQUENCE TO "ORSUSER_IND";
GRANT CREATE ANY TABLE TO "ORSUSER_IND";
GRANT CREATE ANY TRIGGER TO "ORSUSER_IND";
GRANT CREATE ANY VIEW TO "ORSUSER_IND";
GRANT CREATE PROCEDURE TO "ORSUSER_IND";
GRANT CREATE ROLLBACK SEGMENT TO "ORSUSER_IND";
GRANT CREATE TRIGGER TO "ORSUSER_IND";
GRANT CREATE VIEW TO "ORSUSER_IND";
GRANT DEBUG ANY PROCEDURE TO "ORSUSER_IND";
GRANT DELETE ANY TABLE TO "ORSUSER_IND";
GRANT DROP ANY INDEX TO "ORSUSER_IND";
GRANT DROP ANY INDEXTYPE TO "ORSUSER_IND";
GRANT DROP ANY LIBRARY TO "ORSUSER_IND";
GRANT DROP ANY PROCEDURE TO "ORSUSER_IND";
GRANT DROP ANY SEQUENCE TO "ORSUSER_IND";
GRANT DROP ANY TABLE TO "ORSUSER_IND";
GRANT EXECUTE ANY INDEXTYPE TO "ORSUSER_IND";
GRANT EXECUTE ANY LIBRARY TO "ORSUSER_IND";
GRANT EXECUTE ANY PROCEDURE TO "ORSUSER_IND";
GRANT INSERT ANY TABLE TO "ORSUSER_IND";
GRANT SELECT ANY DICTIONARY TO "ORSUSER_IND";
GRANT SELECT ANY SEQUENCE TO "ORSUSER_IND";
GRANT SELECT ANY TABLE TO "ORSUSER_IND";
GRANT UNDER ANY TABLE TO "ORSUSER_IND";
GRANT UNDER ANY VIEW TO "ORSUSER_IND";
GRANT UPDATE ANY TABLE TO "ORSUSER_IND";
GRANT UNLIMITED TABLESPACE TO "ORSUSER_IND";

GRANT RESOURCE TO "ORSUSER_IND";



GRANT DEBUG ANY PROCEDURE, DEBUG CONNECT SESSION TO ORSUSER_IND;

GRANT IMP_FULL_DATABASE TO ORSUSER_IND;

GRANT DBA TO ORSUSER_IND;


