CREATE TABLESPACE       ORSUSER_USA_DAT                     DATAFILE   'ORSUSER_USA_DAT.dbf'    SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE       ORSUSER_160_DAT                     DATAFILE   'ORSUSER_160_DAT.dbf'    SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE       ORSUSER_162_DAT                     DATAFILE   'ORSUSER_162_DAT.dbf'    SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE       ORSUSER_IND_DAT                     DATAFILE   'ORSUSER_IND_DAT.dbf'    SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;


ORSDATA_DEFAULT
ORSDATA_DAT_AUTO
TABLESPACE "ORSDATA_IND_AUTO"
TABLESPACE "ORSDATA_DAT_AUTO"


CREATE TABLESPACE       ORSDATA_DEFAULT                      DATAFILE   'ORSDATA_DEFAULT.dbf'     SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE       ORSDATA_DAT_AUTO                     DATAFILE   'ORSDATA_DAT_AUTO.dbf'    SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
CREATE TABLESPACE       ORSDATA_IND_AUTO                     DATAFILE   'ORSDATA_IND_AUTO.dbf'    SIZE 10M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL UNIFORM SIZE 256K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
