
CREATE  TABLESPACE ORSUSER_PERU_TSPACE      DATAFILE  'D:\app\ACER\oradata\ORSUSER\ORSUSER_PERU_TSPACE.dbf'     size 50M Autoextend on next 1024K maxsize unlimited logging Extent management local autoallocate Segment space management auto;
   

Create user ORSUSER_PERU identified by ORSUSER_PERU default tablespace ORSUSER_PERU_TSPACE;

GRANT "CONNECT" TO "ORSUSER_PERU";
ALTER USER "ORSUSER_PERU" DEFAULT ROLE  ALL;

GRANT ALTER ANY INDEX TO "ORSUSER_PERU";
GRANT ALTER ANY INDEXTYPE TO "ORSUSER_PERU";
GRANT ALTER ANY SEQUENCE TO "ORSUSER_PERU";
GRANT CREATE ANY INDEX TO "ORSUSER_PERU";
GRANT CREATE ANY INDEXTYPE TO "ORSUSER_PERU";
GRANT CREATE ANY PROCEDURE TO "ORSUSER_PERU";
GRANT CREATE ANY SEQUENCE TO "ORSUSER_PERU";
GRANT CREATE ANY TABLE TO "ORSUSER_PERU";
GRANT CREATE ANY TRIGGER TO "ORSUSER_PERU";
GRANT CREATE ANY VIEW TO "ORSUSER_PERU";
GRANT CREATE PROCEDURE TO "ORSUSER_PERU";
GRANT CREATE ROLLBACK SEGMENT TO "ORSUSER_PERU";
GRANT CREATE TRIGGER TO "ORSUSER_PERU";
GRANT CREATE VIEW TO "ORSUSER_PERU";
GRANT DEBUG ANY PROCEDURE TO "ORSUSER_PERU";
GRANT DELETE ANY TABLE TO "ORSUSER_PERU";
GRANT DROP ANY INDEX TO "ORSUSER_PERU";
GRANT DROP ANY INDEXTYPE TO "ORSUSER_PERU";
GRANT DROP ANY LIBRARY TO "ORSUSER_PERU";
GRANT DROP ANY PROCEDURE TO "ORSUSER_PERU";
GRANT DROP ANY SEQUENCE TO "ORSUSER_PERU";
GRANT DROP ANY TABLE TO "ORSUSER_PERU";
GRANT EXECUTE ANY INDEXTYPE TO "ORSUSER_PERU";
GRANT EXECUTE ANY LIBRARY TO "ORSUSER_PERU";
GRANT EXECUTE ANY PROCEDURE TO "ORSUSER_PERU";
GRANT INSERT ANY TABLE TO "ORSUSER_PERU";
GRANT SELECT ANY DICTIONARY TO "ORSUSER_PERU";
GRANT SELECT ANY SEQUENCE TO "ORSUSER_PERU";
GRANT SELECT ANY TABLE TO "ORSUSER_PERU";
GRANT UNDER ANY TABLE TO "ORSUSER_PERU";
GRANT UNDER ANY VIEW TO "ORSUSER_PERU";
GRANT UPDATE ANY TABLE TO "ORSUSER_PERU";
GRANT UNLIMITED TABLESPACE TO "ORSUSER_PERU";

GRANT RESOURCE TO "ORSUSER_PERU";



GRANT DEBUG ANY PROCEDURE, DEBUG CONNECT SESSION TO ORSUSER_PERU;

GRANT IMP_FULL_DATABASE TO ORSUSER_PERU;

GRANT DBA TO ORSUSER_PERU;


